name: deploy

on:
  push:
    branches:
    - main

jobs:

  # scorecard-test-kuttl image build job. Only pushes if a tag with prefix "scorecard-kuttl/v" is present.
  image-scorecard-test-kuttl:
    name: image-scorecard-test-kuttl
    runs-on: ubuntu-20.04
    environment: deploy
    steps:

    - name: set up qemu
      uses: docker/setup-qemu-action@v1

    - name: set up buildx
      uses: docker/setup-buildx-action@v1

    - name: quay.io login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
        registry: quay.io

    # Check out repo before tag step for script.
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: build and push
      uses: docker/build-push-action@v3
      with:
        file: ./images/scorecard-test-kuttl/Dockerfile
        context: .
        # s390x is not supported by the scorecard-test-kuttl base image.
        platforms: linux/amd64
        # Push on tag, or master branch push.
        push: ${{ github.ref == 'refs/heads/master' }}
